/**
 * The tamper-evident run record.
 *
 * A run record binds to the exact bytes of the file SafeSeed emitted (a SHA-256
 * content hash) and states, per field, the reserved range and honesty tier used.
 * It is deliberately a *tamper-evident record*, not "cryptographic proof that the
 * file contains no PII" — the battle-test panel killed the stronger claim, because
 * a signature proves the tool ran, not that the file is free of personal data.
 */
import { CATALOG_VERSION, getEntry } from "./catalog.js";
import { sha256Hex } from "./hash.js";
import { canonicalColumn } from "./csv.js";
import type { GeneratedDataset } from "./generate.js";
import type { FieldType, Tier } from "./types.js";

// 0.2.0 adds a per-column `sha256` to every FieldRecord (the basis for opt-in
// column-scoped verify). It is purely additive — strict whole-file verify is
// unchanged, and a 0.1.0 record without per-column hashes still verifies strictly.
export const SAFESEED_VERSION = "0.2.0";

export interface FieldRecord {
  name: string;
  type: FieldType;
  tier: Tier;
  citation: string;
  claim: string;
  /**
   * SHA-256 over a canonical serialization of this column's values (see
   * `canonicalColumn`). Lets column-scoped verify re-check one declared column
   * independently of the rest of the file. Optional only for backward compat with
   * 0.1.0 records that predate it; `makeRunRecord` always emits it.
   */
  sha256?: string;
}

export interface RunRecord {
  safeseedVersion: string;
  catalogVersion: string;
  seed: number;
  rowCount: number;
  columns: string[];
  fields: FieldRecord[];
  /** SHA-256 of the exact emitted file content. */
  contentSha256: string;
  /** Honest statement of what this record attests and what it does NOT. */
  attestation: string;
  /** Optional caller-supplied timestamp; omitted by default to keep records deterministic. */
  generatedAt?: string;
}

export const ATTESTATION = [
  "This run record attests that the named dataset was generated by SafeSeed from",
  "standards-reserved ranges, with no real input data. It is a tamper-evident",
  "record, not a cryptographic proof that the file contains no personal data. It",
  "attests the generator and binds to this file's content hash; it says nothing",
  "about edits made after generation.",
  '"Not derived from production data" is not the same claim as "not personal data."',
  "Re-verify against the actual artifact in your pipeline (GDPR Art. 25/32 control",
  "for non-production environments; not a scope-out from privacy law).",
].join(" ");

export async function makeRunRecord(
  dataset: GeneratedDataset,
  csv: string,
  opts?: { generatedAt?: string },
): Promise<RunRecord> {
  const contentSha256 = await sha256Hex(csv);
  const fields: FieldRecord[] = await Promise.all(
    dataset.schema.map(async (f, c) => {
      const entry = getEntry(f.type);
      const column = dataset.rows.map((row) => row[c] ?? "");
      return {
        name: f.name,
        type: f.type,
        tier: entry.tier,
        citation: entry.citation,
        claim: entry.claim,
        sha256: await sha256Hex(canonicalColumn(column)),
      };
    }),
  );
  return {
    safeseedVersion: SAFESEED_VERSION,
    catalogVersion: dataset.catalogVersion ?? CATALOG_VERSION,
    seed: dataset.seed,
    rowCount: dataset.rows.length,
    columns: dataset.columns,
    fields,
    contentSha256,
    attestation: ATTESTATION,
    ...(opts?.generatedAt !== undefined ? { generatedAt: opts.generatedAt } : {}),
  };
}
