/**
 * The tamper-evident run record.
 *
 * A run record binds to the exact bytes of the file SafeSeed emitted (a SHA-256
 * content hash) and states, per field, the reserved range and honesty tier used.
 * It is deliberately a *tamper-evident record*, not "cryptographic proof that the
 * file contains no PII" — the battle-test panel killed the stronger claim, because
 * a signature proves the tool ran, not that the file is free of personal data.
 */
import { CATALOG_VERSION, getEntry } from "./catalog.js";
import { sha256Hex } from "./hash.js";
import type { GeneratedDataset } from "./generate.js";
import type { FieldType, Tier } from "./types.js";

export const SAFESEED_VERSION = "0.1.0";

export interface FieldRecord {
  name: string;
  type: FieldType;
  tier: Tier;
  citation: string;
  claim: string;
}

export interface RunRecord {
  safeseedVersion: string;
  catalogVersion: string;
  seed: number;
  rowCount: number;
  columns: string[];
  fields: FieldRecord[];
  /** SHA-256 of the exact emitted file content. */
  contentSha256: string;
  /** Honest statement of what this record attests and what it does NOT. */
  attestation: string;
  /** Optional caller-supplied timestamp; omitted by default to keep records deterministic. */
  generatedAt?: string;
}

export const ATTESTATION = [
  "This run record attests that the named dataset was generated by SafeSeed from",
  "standards-reserved ranges, with no real input data. It is a tamper-evident",
  "record, not a cryptographic proof that the file contains no personal data. It",
  "attests the generator and binds to this file's content hash; it says nothing",
  "about edits made after generation.",
  '"Not derived from production data" is not the same claim as "not personal data."',
  "Re-verify against the actual artifact in your pipeline (GDPR Art. 25/32 control",
  "for non-production environments; not a scope-out from privacy law).",
].join(" ");

export async function makeRunRecord(
  dataset: GeneratedDataset,
  csv: string,
  opts?: { generatedAt?: string },
): Promise<RunRecord> {
  const contentSha256 = await sha256Hex(csv);
  const fields: FieldRecord[] = dataset.schema.map((f) => {
    const entry = getEntry(f.type);
    return {
      name: f.name,
      type: f.type,
      tier: entry.tier,
      citation: entry.citation,
      claim: entry.claim,
    };
  });
  return {
    safeseedVersion: SAFESEED_VERSION,
    catalogVersion: dataset.catalogVersion ?? CATALOG_VERSION,
    seed: dataset.seed,
    rowCount: dataset.rows.length,
    columns: dataset.columns,
    fields,
    contentSha256,
    attestation: ATTESTATION,
    ...(opts?.generatedAt !== undefined ? { generatedAt: opts.generatedAt } : {}),
  };
}
